export const SPRITE_PALETTE = {
  a: 'var(--color-accent)',
  w: 'var(--color-ink)',
  m: 'var(--color-muted)',
  k: 'var(--color-bg)',
  g: 'var(--color-pitch-line)',
  s: 'var(--color-score)',
  r: 'var(--color-team-home)',
  b: 'var(--color-team-away)',
} as const

export type SpritePaletteKey = keyof typeof SPRITE_PALETTE

export const SPRITES = {
  ball: [
    '..wwww..',
    '.wkkwww.',
    'wwkkwwkw',
    'wwwwwkkw',
    'wkwwwwww',
    'wkkwwkww',
    '.wwwkkw.',
    '..wwww..',
  ],
  trophy: [
    'ssssssss',
    's.ssss.s',
    's.ssss.s',
    '.ssssss.',
    '..ssss..',
    '...ss...',
    '..ssss..',
    '.ssssss.',
  ],
  shirt: [
    '.aaa..aaa.',
    'aaaaaaaaaa',
    'aaaaaaaaaa',
    'aa.aaaa.aa',
    '...aaaa...',
    '...aaaa...',
    '...aaaa...',
    '...aaaa...',
  ],
  cursor: ['a....', 'aa...', 'aaa..', 'aaaa.', 'aaa..', 'aa...', 'a....'],
  chef: [
    '.ww..ww.',
    'wwwwwwww',
    'wwwwwwww',
    '.wwwwww.',
    '.wwwwww.',
    '.mmmmmm.',
    '.wwwwww.',
    '.wwwwww.',
  ],
  controller: [
    '.mmmmmmmmmm.',
    'mmwmmmmmmmmm',
    'mwwwmmmmmamm',
    'mmwmmmmmammm',
    'mmmmmmmmmmmm',
    'mmm......mmm',
  ],
  terminal: [
    'mmmmmmmmmm',
    'mkkkkkkkkm',
    'mkakkkkkkm',
    'mkkakkkkkm',
    'mkakkwwwkm',
    'mkkkkkkkkm',
    'mmmmmmmmmm',
    '...mmmm...',
  ],
  book: [
    '.aaaaaaa',
    'aaaaaaaa',
    'aawwwwaa',
    'aaaaaaaa',
    'aawwwaaa',
    'aaaaaaaa',
    'awwwwwww',
    '.aaaaaaa',
  ],
  rocket: [
    '...ww...',
    '..wwww..',
    '..wwww..',
    '..wkkw..',
    '..wkkw..',
    '..wwww..',
    '.wwwwww.',
    'ww.ww.ww',
    '...aa...',
    '...ss...',
  ],
  clock: [
    '...ss...',
    '..ssss..',
    '.swwwws.',
    'swwkwwws',
    'swwkwwws',
    'swwwkkws',
    '.swwwws.',
    '..ssss..',
  ],
  crest: [
    'rrrrbbbb',
    'rrrrbbbb',
    'rrwwwwbb',
    'rrwwwwbb',
    '.rrwwbb.',
    '.rrwwbb.',
    '..rrbb..',
    '...rb...',
  ],
  goal: [
    'wwwwwwwwww',
    'w.m.m.m.mw',
    'wm.m.m.m.w',
    'w.m.m.m.mw',
    'wm.m.m.m.w',
    'w........w',
  ],
} satisfies Record<string, string[]>

export type SpriteName = keyof typeof SPRITES
